require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '13.5'

def shared_pods
  config = use_native_modules!
  use_react_native!(path: config['reactNativePath'])

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Notifications', path: "#{permissions_path}/Notifications.podspec"

  pod 'Realm', '~> 10.1.1', modular_headers: true
  pod 'RealmSwift', '~> 10.1.1', modular_headers: true
  pod 'Alamofire', '~> 4.9.1'
  pod 'KeychainAccess', '~> 4.2.0'
  pod 'ZIPFoundation', '~> 0.9.11'
  pod 'PromisesSwift', modular_headers: true
  pod 'PromisesObjC', modular_headers: true

  use_flipper!('Flipper' => '0.62.0') # should match the version of your Flipper client app
  post_install do |installer|
    flipper_post_install(installer)

    ## Fix for Flipper-Folly on iOS 14.5
    find_and_replace('Pods/Flipper-Folly/folly/synchronization/DistributedMutex-inl.h',
                     'atomic_notify_one(state)', 'folly::atomic_notify_one(state)')

    find_and_replace('Pods/Headers/Private/RCT-Folly/folly/synchronization/DistributedMutex-inl.h',
                     'atomic_notify_one(state)', 'folly::atomic_notify_one(state)')

    find_and_replace('Pods/Flipper-Folly/folly/synchronization/DistributedMutex-inl.h',
                     'atomic_wait_until(&state, previous | data, deadline)', 'folly::atomic_wait_until(&state, previous | data, deadline)')
  end
end

def find_and_replace(dir, findstr, replacestr)
  Dir[dir].each do |name|
    text = File.read(name)
    replace = text.gsub(findstr, replacestr)
    next unless text != replace

    puts 'Fix: ' + name
    File.open(name, 'w') { |file| file.puts replace }
    STDOUT.flush
  end
  Dir[dir + '*/'].each(&method(:find_and_replace))
end

target 'BT' do
  shared_pods

  target 'BTTests' do
    inherit! :search_paths
  end
end
